// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt80Zq0k06FyyRhO_a53ZLr2m5hMb-ku0',
    appId: '1:854094728718:android:19e65f6a1abe973defb65f',
    messagingSenderId: '854094728718',
    projectId: 'mokamal-platform',
    storageBucket: 'mokamal-platform.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPKzvJuwbAk4eTy5axDfWBnjGcTinggPY',
    appId: '1:854094728718:ios:90ede3d65e6593f6efb65f',
    messagingSenderId: '854094728718',
    projectId: 'mokamal-platform',
    storageBucket: 'mokamal-platform.firebasestorage.app',
    iosBundleId: 'com.user.mokamalOnlinePlatform',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXuIvkhrnyeRq2HCqjNFZpV4t-MYTx_q8',
    appId: '1:770079601895:web:a35b3784e16c45fed59e42',
    messagingSenderId: '770079601895',
    projectId: 'mokamal-platform',
    authDomain: 'mokamal-platform.firebaseapp.com',
    storageBucket: 'mokamal-platform.firebasestorage.app',
    measurementId: 'G-WJLFESLZT2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXuIvkhrnyeRq2HCqjNFZpV4t-MYTx_q8',
    appId: '1:770079601895:web:0e144d048aa1928ad59e42',
    messagingSenderId: '770079601895',
    projectId: 'mokamal-platform',
    authDomain: 'mokamal-platform.firebaseapp.com',
    storageBucket: 'mokamal-platform.firebasestorage.app',
    measurementId: 'G-6W9KCRL36D',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfqMVqKF-6EhB90YhBGXl6Zpz93VrSR-k',
    appId: '1:770079601895:ios:f1ec0e7cde2e28b0d59e42',
    messagingSenderId: '770079601895',
    projectId: 'mokamal-platform',
    storageBucket: 'mokamal-platform.firebasestorage.app',
    iosBundleId: 'com.example.mokamalOnlinePlatform',
  );
}
